"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Circle, DoorOpen, Layers, Minus, MousePointer2, Plus, Redo2, Save, Trash2, Undo2, Copy, Type, Warehouse, CookingPot, PanelTop } from "lucide-react";
import { Circle as KonvaCircle, Group, Layer, Line, Rect, Stage, Text } from "react-konva";
import { createClient } from "@/lib/supabase/client";

export type FloorObjectType = "round-table" | "square-table" | "rectangle-table" | "wall" | "divider" | "door" | "label" | "bar" | "kitchen";
export type FloorObject = { id: string; type: FloorObjectType; x: number; y: number; width: number; height: number; rotation: number; zIndex: number; label?: string; displayNumber?: number; seats?: number; active?: boolean };
export type FloorLayout = { objects: FloorObject[]; viewport: { x: number; y: number; scale: number } };
const initial = (layout: FloorLayout): FloorLayout => ({ objects: layout?.objects ?? [], viewport: layout?.viewport ?? { x: 0, y: 0, scale: 1 } });
const palette: { type: FloorObjectType; name: string; icon: typeof Circle }[] = [
  { type: "round-table", name: "Round table", icon: Circle }, { type: "square-table", name: "Square table", icon: PanelTop }, { type: "rectangle-table", name: "Rectangle table", icon: PanelTop },
  { type: "wall", name: "Wall", icon: Minus }, { type: "divider", name: "Divider", icon: Minus }, { type: "door", name: "Door", icon: DoorOpen }, { type: "label", name: "Label", icon: Type }, { type: "bar", name: "Bar", icon: Warehouse }, { type: "kitchen", name: "Kitchen", icon: CookingPot }
];
function fresh(type: FloorObjectType, count: number): FloorObject { const table = type.includes("table"); const dimensions = type === "round-table" || type === "square-table" ? [92, 92] : type === "rectangle-table" || type === "bar" || type === "kitchen" ? [160, 72] : type === "wall" || type === "divider" ? [180, 8] : [120, 55]; return { id: crypto.randomUUID(), type, x: 180 + count * 12, y: 130 + count * 12, width: dimensions[0], height: dimensions[1], rotation: 0, zIndex: count, ...(table ? { displayNumber: count + 1, seats: type === "rectangle-table" ? 6 : 4, active: true } : {}), ...(type === "label" ? { label: "New label" } : {}) }; }
const isTable = (o: FloorObject) => o.type.endsWith("table");

export function FloorPlanEditor({ initialLayout, isAdmin }: { initialLayout: FloorLayout; isAdmin: boolean }) {
  const [layout, setLayout] = useState(() => initial(initialLayout)); const [history, setHistory] = useState<FloorLayout[]>([]); const [future, setFuture] = useState<FloorLayout[]>([]);
  const [edit, setEdit] = useState(false); const [selected, setSelected] = useState<string[]>([]); const [dialog, setDialog] = useState<FloorObject | null>(null); const [status, setStatus] = useState("Saved"); const [panning, setPanning] = useState<{ x: number; y: number; vx: number; vy: number } | null>(null); const [drag, setDrag] = useState<{ id: string; x: number; y: number } | null>(null); const stage = useRef<HTMLDivElement>(null);
  const commit = useCallback((next: FloorLayout) => { setHistory(h => [...h.slice(-39), layout]); setFuture([]); setLayout(next); setStatus("Unsaved changes"); }, [layout]);
  const updateObject = (id: string, patch: Partial<FloorObject>) => commit({ ...layout, objects: layout.objects.map(o => o.id === id ? { ...o, ...patch } : o) });
  const selectedObject = layout.objects.find(o => o.id === selected[0]);
  const add = (type: FloorObjectType) => { const obj = fresh(type, layout.objects.length); commit({ ...layout, objects: [...layout.objects, obj] }); setSelected([obj.id]); };
  const save = async () => { setStatus("Saving…"); const supabase = createClient(); const { error } = await supabase.from("floor_layouts").upsert({ id: 1, layout, updated_by: (await supabase.auth.getUser()).data.user?.id }); setStatus(error ? `Could not save: ${error.message}` : "Saved"); };
  const undo = () => { const prior = history.at(-1); if (!prior) return; setFuture(f => [layout, ...f]); setHistory(h => h.slice(0, -1)); setLayout(prior); };
  const redo = () => { const next = future[0]; if (!next) return; setHistory(h => [...h, layout]); setFuture(f => f.slice(1)); setLayout(next); };
  const remove = () => { if (!selected.length) return; commit({ ...layout, objects: layout.objects.filter(o => !selected.includes(o.id)) }); setSelected([]); };
  const duplicate = () => { const sources = layout.objects.filter(o => selected.includes(o.id)); if (!sources.length) return; const copies = sources.map((o, i) => ({ ...o, id: crypto.randomUUID(), x: o.x + 24, y: o.y + 24, zIndex: layout.objects.length + i, displayNumber: isTable(o) ? Math.max(0, ...layout.objects.map(x => x.displayNumber ?? 0)) + i + 1 : o.displayNumber })); commit({ ...layout, objects: [...layout.objects, ...copies] }); setSelected(copies.map(o => o.id)); };
  useEffect(() => { const key = (e: KeyboardEvent) => { if (!edit) return; if (e.key === "Delete" || e.key === "Backspace") { e.preventDefault(); remove(); } if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "z") { e.preventDefault(); e.shiftKey ? redo() : undo(); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); });
  const point = (event: React.PointerEvent | React.WheelEvent) => { const r = stage.current?.getBoundingClientRect(); return { x: (event.clientX - (r?.left ?? 0) - layout.viewport.x) / layout.viewport.scale, y: (event.clientY - (r?.top ?? 0) - layout.viewport.y) / layout.viewport.scale }; };
  const onWheel = (e: React.WheelEvent) => { e.preventDefault(); const before = point(e), scale = Math.min(2.5, Math.max(.35, layout.viewport.scale * (e.deltaY > 0 ? .9 : 1.1))); commit({ ...layout, viewport: { scale, x: e.clientX - (stage.current?.getBoundingClientRect().left ?? 0) - before.x * scale, y: e.clientY - (stage.current?.getBoundingClientRect().top ?? 0) - before.y * scale } }); };
  const ordered = useMemo(() => [...layout.objects].sort((a,b) => a.zIndex - b.zIndex), [layout.objects]);
  return <section className="-m-6 h-[calc(100vh-0px)] overflow-hidden bg-white md:-m-10"><div className="flex h-full flex-col">
    <header className="z-10 flex min-h-16 items-center gap-3 border-b bg-white px-4 shadow-sm"><div><p className="text-[10px] font-bold tracking-[.18em] text-primary">FLOOR PLAN</p><h1 className="text-lg font-bold">Dining room</h1></div><div className="ml-auto flex items-center gap-2"><span className="hidden text-xs text-muted-foreground sm:inline">{status}</span>{isAdmin && <button onClick={() => { setEdit(v => !v); setSelected([]); }} className={`rounded-md px-3 py-2 text-sm font-semibold ${edit ? "bg-primary text-white" : "border bg-white"}`}>{edit ? "Edit Mode ON" : "Edit Mode OFF"}</button>}<button onClick={save} disabled={!isAdmin} className="inline-flex items-center gap-2 rounded-md bg-zinc-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-40"><Save size={15}/>Save</button></div></header>
    <div className="flex min-h-0 flex-1">{edit && <aside className="z-10 w-48 shrink-0 overflow-y-auto border-r bg-zinc-50 p-3"><p className="mb-2 px-1 text-xs font-bold uppercase tracking-wider text-muted-foreground">Add object</p><div className="space-y-1">{palette.map(({type,name,icon: Icon}) => <button key={type} onClick={() => add(type)} className="flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-sm hover:bg-white hover:shadow-sm"><Icon size={15}/>{name}</button>)}</div><div className="mt-5 border-t pt-4"><p className="mb-2 text-xs font-bold uppercase tracking-wider text-muted-foreground">Arrange</p><div className="grid grid-cols-2 gap-1"><button onClick={undo} disabled={!history.length} className="tool"><Undo2 size={15}/>Undo</button><button onClick={redo} disabled={!future.length} className="tool"><Redo2 size={15}/>Redo</button><button onClick={duplicate} className="tool"><Copy size={15}/>Copy</button><button onClick={remove} className="tool text-red-600"><Trash2 size={15}/>Delete</button></div></div></aside>}
      <main ref={stage} className={`relative min-w-0 flex-1 ${edit ? "cursor-grab" : ""}`} onWheel={onWheel} onPointerDown={e => { if (edit && e.target === e.currentTarget) setPanning({x:e.clientX,y:e.clientY,vx:layout.viewport.x,vy:layout.viewport.y}); }} onPointerMove={e => { if (panning) setLayout(l => ({...l,viewport:{...l.viewport,x:panning.vx+e.clientX-panning.x,y:panning.vy+e.clientY-panning.y}})); if (drag) { const p=point(e); setLayout(l => ({...l,objects:l.objects.map(o=>o.id===drag.id?{...o,x:p.x-drag.x,y:p.y-drag.y}:o)})); } }} onPointerUp={() => { if (panning || drag) setStatus("Unsaved changes"); setPanning(null); setDrag(null); }}>
        <Stage width={stage.current?.clientWidth ?? 1000} height={stage.current?.clientHeight ?? 700} x={layout.viewport.x} y={layout.viewport.y} scaleX={layout.viewport.scale} scaleY={layout.viewport.scale} className="h-full w-full" onPointerDown={(e: React.PointerEvent) => { if (e.target === e.currentTarget) setSelected([]); }}><Layer>{ordered.map(o => <FloorNode key={o.id} object={o} selected={selected.includes(o.id)} edit={edit} onSelect={(multi) => { if (!edit) { if (isTable(o)) setDialog(o); return; } setSelected(s => multi ? (s.includes(o.id) ? s.filter(id=>id!==o.id) : [...s,o.id]) : [o.id]); }} onDragStart={e => { if (!edit) return; const p=point(e); setDrag({id:o.id,x:p.x-o.x,y:p.y-o.y}); }} />)}</Layer></Stage>
        <div className="absolute bottom-4 left-4 flex rounded-md border bg-white p-1 shadow-sm"><button onClick={() => commit({...layout,viewport:{...layout.viewport,scale:Math.min(2.5,layout.viewport.scale+0.15)}})} className="p-2"><Plus size={16}/></button><span className="px-2 py-2 text-xs text-muted-foreground">{Math.round(layout.viewport.scale*100)}%</span><button onClick={() => commit({...layout,viewport:{...layout.viewport,scale:Math.max(.35,layout.viewport.scale-.15)}})} className="p-2"><Minus size={16}/></button></div>
      </main>{edit && <Inspector object={selectedObject} onChange={updateObject} onLayer={direction => selectedObject && updateObject(selectedObject.id,{zIndex:selectedObject.zIndex+direction})}/>}</div></div>{dialog && <div className="fixed inset-0 z-30 grid place-items-center bg-black/20 p-4" onClick={() => setDialog(null)}><div className="w-full max-w-xs rounded-xl bg-white p-6 shadow-xl" onClick={e=>e.stopPropagation()}><p className="text-xs font-bold tracking-widest text-primary">TABLE</p><h2 className="mt-1 text-2xl font-bold">Table {dialog.displayNumber}</h2><p className="mt-2 text-sm text-muted-foreground">Ordering will be available here soon.</p><button onClick={()=>setDialog(null)} className="mt-5 rounded-md bg-zinc-900 px-3 py-2 text-sm text-white">Close</button></div></div>}</section>;
}

function FloorNode({ object: o, selected, edit, onSelect, onDragStart }: { object: FloorObject; selected: boolean; edit: boolean; onSelect: (multi: boolean) => void; onDragStart: (e: React.PointerEvent) => void }) {
  const common = { onPointerDown: (e: React.PointerEvent) => { e.stopPropagation(); onSelect(e.ctrlKey || e.metaKey); onDragStart(e); }, style: { cursor: edit ? "move" : isTable(o) ? "pointer" : "default" } };
  const selectedStroke = selected ? "#b45309" : "#a1a1aa";
  if (o.type === "round-table") return <Group transform={`translate(${o.x} ${o.y}) rotate(${o.rotation} ${o.width/2} ${o.height/2})`} {...common}><KonvaCircle cx={o.width/2} cy={o.height/2} r={o.width/2} fill="white" stroke={selectedStroke} strokeWidth={selected ? 3 : 2}/><Text x={0} y={o.height/2+5} textAnchor="middle" dx={o.width/2} fontSize={18} fontWeight="700" fill="#27272a">{o.displayNumber}</Text></Group>;
  if (o.type === "wall" || o.type === "divider") return <Group transform={`translate(${o.x} ${o.y}) rotate(${o.rotation})`} {...common}><Rect width={o.width} height={o.height} fill={o.type === "wall" ? "#3f3f46" : "#d4d4d8"} stroke={selected ? "#b45309" : undefined} strokeWidth={selected ? 3 : 0}/></Group>;
  if (o.type === "door") return <Group transform={`translate(${o.x} ${o.y}) rotate(${o.rotation})`} {...common}><Line points={[0,o.height,0,0,o.width,0]} stroke={selectedStroke} strokeWidth={2}/><Line points={[0,o.height,o.width,o.height]} stroke="#a1a1aa" strokeWidth={1} strokeDasharray="4 3"/><path d={`M 0 ${o.height} A ${o.width} ${o.height} 0 0 1 ${o.width} 0`} fill="none" stroke="#a1a1aa" strokeWidth="1.5"/></Group>;
  const title = o.type === "label" ? o.label : o.type === "bar" ? "BAR" : o.type === "kitchen" ? "KITCHEN" : o.displayNumber;
  const fill = o.type === "label" ? "transparent" : "white";
  return <Group transform={`translate(${o.x} ${o.y}) rotate(${o.rotation} ${o.width/2} ${o.height/2})`} {...common}><Rect width={o.width} height={o.height} rx={o.type === "label" ? 0 : 8} fill={fill} stroke={o.type === "label" ? "transparent" : selectedStroke} strokeWidth={selected ? 3 : 2}/><Text x={o.width/2} y={o.height/2+5} textAnchor="middle" fontSize={o.type === "label" ? 17 : 16} fontWeight="700" fill="#27272a">{title}</Text></Group>;
}
function Inspector({ object, onChange, onLayer }: { object?: FloorObject; onChange: (id:string, patch:Partial<FloorObject>)=>void; onLayer:(direction:number)=>void }) {
  if (!object) return <aside className="hidden w-60 shrink-0 border-l bg-zinc-50 p-5 lg:block"><MousePointer2 className="mb-3 text-muted-foreground" size={20}/><h2 className="font-semibold">Inspector</h2><p className="mt-1 text-sm text-muted-foreground">Select an object to edit its details.</p></aside>;
  const field = (label: string, key: keyof FloorObject, value: string | number) => <label className="block text-xs font-medium text-muted-foreground">{label}<input className="mt-1 w-full rounded border bg-white px-2 py-1.5 text-sm text-foreground" value={value} onChange={e => onChange(object.id, {[key]: key === "label" ? e.target.value : Number(e.target.value)})}/></label>;
  return <aside className="w-60 shrink-0 overflow-y-auto border-l bg-zinc-50 p-4"><div className="flex items-center gap-2"><Layers size={16}/><h2 className="font-semibold">{object.type.replaceAll("-", " ")}</h2></div><div className="mt-4 space-y-3">{isTable(object) && <>{field("Display number", "displayNumber", object.displayNumber ?? 1)}{field("Seat count", "seats", object.seats ?? 0)}</>}{object.type === "label" && field("Text", "label", object.label ?? "")}{field("Width", "width", object.width)}{field("Height", "height", object.height)}{field("Rotation", "rotation", object.rotation)}<div className="grid grid-cols-2 gap-2">{field("X", "x", Math.round(object.x))}{field("Y", "y", Math.round(object.y))}</div><div className="border-t pt-3"><p className="mb-2 text-xs font-medium text-muted-foreground">Layer order</p><div className="flex gap-2"><button onClick={()=>onLayer(1)} className="rounded border bg-white px-2 py-1 text-xs">Bring forward</button><button onClick={()=>onLayer(-1)} className="rounded border bg-white px-2 py-1 text-xs">Send back</button></div></div></div></aside>;
}
