"use client";

import { useMemo, useState, useTransition } from "react";
import { CheckCircle2, Pencil, Plus, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { saveCategory, saveProduct, setCategoryActive, setCategorySort, setProductActive } from "@/app/app/products/actions";

type Category = { id: string; name: string; description: string; color: string | null; sort_order: number; active: boolean; printer_destination: "internal" | "none"; product_count: number };
type Product = { id: string; category_id: string; name: string; price: number; tax_rate: number; cost_price: number; sku: string | null; barcode: string | null; printer_destination: "internal" | "none"; track_inventory: boolean; active: boolean; sort_order: number };
type Notice = { error?: string; success?: string };
const money = new Intl.NumberFormat(undefined, { style: "currency", currency: "USD" });
const input = "mt-1 w-full rounded-md border bg-background px-3 py-2 text-sm";

function Status({ active }: { active: boolean }) { return <span className={`rounded-full px-2 py-1 text-xs font-semibold ${active ? "bg-emerald-100 text-emerald-800" : "bg-muted text-muted-foreground"}`}>{active ? "Active" : "Inactive"}</span>; }
function Modal({ title, children, close }: { title: string; children: React.ReactNode; close: () => void }) { return <div className="fixed inset-0 z-50 flex items-end bg-black/40 p-0 sm:items-center sm:justify-center sm:p-4" role="dialog" aria-modal="true"><section className="max-h-[95vh] w-full overflow-y-auto rounded-t-xl bg-card p-5 shadow-xl sm:max-w-2xl sm:rounded-xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><Button variant="ghost" onClick={close}>Close</Button></div>{children}</section></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium">{label}{children}</label>; }

export function ProductsManager({ categories, products }: { categories: Category[]; products: Product[] }) {
  const [categorySearch, setCategorySearch] = useState(""); const [productSearch, setProductSearch] = useState(""); const [categoryFilter, setCategoryFilter] = useState("all"); const [statusFilter, setStatusFilter] = useState("all"); const [categoryModal, setCategoryModal] = useState<Category | null | "new">(null); const [productModal, setProductModal] = useState<Product | null | "new">(null); const [notice, setNotice] = useState<Notice>({}); const [pending, startTransition] = useTransition();
  const filteredCategories = useMemo(() => categories.filter(c => c.name.toLowerCase().includes(categorySearch.toLowerCase())).sort((a,b) => a.sort_order - b.sort_order || a.name.localeCompare(b.name)), [categories, categorySearch]);
  const filteredProducts = useMemo(() => products.filter(p => (p.name.toLowerCase().includes(productSearch.toLowerCase()) || (p.sku ?? "").toLowerCase().includes(productSearch.toLowerCase()) || (p.barcode ?? "").includes(productSearch)) && (categoryFilter === "all" || p.category_id === categoryFilter) && (statusFilter === "all" || String(p.active) === statusFilter)).sort((a,b) => a.sort_order - b.sort_order || a.name.localeCompare(b.name)), [products, productSearch, categoryFilter, statusFilter]);
  const run = (work: () => Promise<Notice>) => startTransition(async () => { const result = await work(); setNotice(result); });
  const submitCategory = (form: FormData) => run(async () => { const result = await saveCategory({ id: categoryModal === "new" ? undefined : categoryModal?.id, name: form.get("name"), description: form.get("description"), color: form.get("color") || null, sort_order: form.get("sort_order"), active: form.get("active") === "on", printer_destination: form.get("printer_destination") }); if (result.success) setCategoryModal(null); return result; });
  const submitProduct = (form: FormData) => run(async () => { const result = await saveProduct({ id: productModal === "new" ? undefined : productModal?.id, category_id: form.get("category_id"), name: form.get("name"), price: form.get("price"), tax_rate: form.get("tax_rate"), cost_price: form.get("cost_price"), sku: form.get("sku") || null, barcode: form.get("barcode") || null, printer_destination: form.get("printer_destination"), track_inventory: form.get("track_inventory") === "on", active: form.get("active") === "on", sort_order: form.get("sort_order") }); if (result.success) setProductModal(null); return result; });
  return <div className="space-y-10">
    {notice.error && <p role="alert" className="rounded-md bg-red-50 p-3 text-sm text-red-700">{notice.error}</p>}{notice.success && <p role="status" className="flex items-center gap-2 rounded-md bg-emerald-50 p-3 text-sm text-emerald-800"><CheckCircle2 className="size-4" />{notice.success}</p>}
    <section><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">CATALOG</p><h1 className="text-3xl font-bold tracking-tight">Products</h1><p className="mt-1 text-muted-foreground">Manage categories and products used by new orders.</p></div><Button className="gap-2" onClick={() => setCategoryModal("new")}><Plus className="size-4" />Add Category</Button></div>
    <div className="mt-5 rounded-lg border bg-card"><div className="border-b p-4"><label className="relative block"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><input className="w-full rounded-md border py-2 pl-9 pr-3 text-sm" value={categorySearch} onChange={e => setCategorySearch(e.target.value)} placeholder="Search categories" /></label></div>{filteredCategories.length === 0 ? <p className="p-8 text-center text-sm text-muted-foreground">No categories match your search. Add a category to get started.</p> : <div className="divide-y">{filteredCategories.map(c => <div key={c.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="size-4 shrink-0 rounded-full border" style={{ backgroundColor: c.color || "transparent" }} /><div><p className="font-semibold">{c.name} <Status active={c.active} /></p><p className="text-sm text-muted-foreground">{c.description || "No description"} · {c.product_count} product{c.product_count === 1 ? "" : "s"} · {c.printer_destination}</p></div></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setCategoryModal(c)}><Pencil className="mr-1 size-3" />Edit</Button><Button size="sm" variant="ghost" disabled={pending || filteredCategories.indexOf(c) === 0} onClick={() => run(() => setCategorySort(c.id, filteredCategories[filteredCategories.indexOf(c) - 1].sort_order - 1))}>Earlier</Button><Button size="sm" variant="ghost" disabled={pending || filteredCategories.indexOf(c) === filteredCategories.length - 1} onClick={() => run(() => setCategorySort(c.id, filteredCategories[filteredCategories.indexOf(c) + 1].sort_order + 1))}>Later</Button><Button size="sm" variant="ghost" disabled={pending} onClick={() => run(() => setCategoryActive(c.id, !c.active))}>{c.active ? "Deactivate" : "Activate"}</Button></div></div>)}</div>}</div></section>
    <section><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-bold">Products</h2><p className="text-muted-foreground">Inactive products stay in history but are unavailable for new orders.</p></div><Button className="gap-2" onClick={() => setProductModal("new")}><Plus className="size-4" />Add Product</Button></div><div className="mt-5 rounded-lg border bg-card"><div className="grid gap-3 border-b p-4 md:grid-cols-3"><label className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><input className="w-full rounded-md border py-2 pl-9 pr-3 text-sm" value={productSearch} onChange={e => setProductSearch(e.target.value)} placeholder="Search products, SKU or barcode" /></label><select className="rounded-md border px-3 py-2 text-sm" value={categoryFilter} onChange={e => setCategoryFilter(e.target.value)}><option value="all">All categories</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="rounded-md border px-3 py-2 text-sm" value={statusFilter} onChange={e => setStatusFilter(e.target.value)}><option value="all">Active and inactive</option><option value="true">Active</option><option value="false">Inactive</option></select></div>{filteredProducts.length === 0 ? <p className="p-8 text-center text-sm text-muted-foreground">No products match these filters. Add a product when you are ready.</p> : <div className="divide-y">{filteredProducts.map(p => <div key={p.id} className="flex flex-col gap-3 p-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-semibold">{p.name} <Status active={p.active} /></p><p className="text-sm text-muted-foreground">{categories.find(c => c.id === p.category_id)?.name ?? "Unknown category"} · {money.format(p.price)} · Tax {p.tax_rate}% · SKU {p.sku || "—"} · {p.printer_destination}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setProductModal(p)}><Pencil className="mr-1 size-3" />Edit</Button><Button size="sm" variant="ghost" disabled={pending} onClick={() => run(() => setProductActive(p.id, !p.active))}>{p.active ? "Deactivate" : "Activate"}</Button></div></div>)}</div>}</div></section>
    {categoryModal && <Modal title={categoryModal === "new" ? "Add category" : "Edit category"} close={() => setCategoryModal(null)}><form action={submitCategory} className="grid gap-4 sm:grid-cols-2"><Field label="Name"><input required name="name" defaultValue={categoryModal === "new" ? "" : categoryModal.name} className={input} /></Field><Field label="Sort order"><input required name="sort_order" type="number" step="1" defaultValue={categoryModal === "new" ? 0 : categoryModal.sort_order} className={input} /></Field><Field label="Description"><textarea name="description" defaultValue={categoryModal === "new" ? "" : categoryModal.description} className={input} /></Field><Field label="Color"><input name="color" type="color" defaultValue={categoryModal === "new" ? "#8a4b2a" : categoryModal.color || "#8a4b2a"} className={input} /></Field><Field label="Printer destination"><select name="printer_destination" defaultValue={categoryModal === "new" ? "internal" : categoryModal.printer_destination} className={input}><option value="internal">Internal</option><option value="none">None</option></select></Field><label className="flex items-center gap-2 text-sm font-medium"><input name="active" type="checkbox" defaultChecked={categoryModal === "new" || categoryModal.active} />Active</label><div className="sm:col-span-2 flex justify-end"><Button disabled={pending} type="submit">{pending ? "Saving…" : "Save category"}</Button></div></form></Modal>}
    {productModal && <Modal title={productModal === "new" ? "Add product" : "Edit product"} close={() => setProductModal(null)}><form action={submitProduct} className="grid gap-4 sm:grid-cols-2"><Field label="Name"><input required name="name" defaultValue={productModal === "new" ? "" : productModal.name} className={input} /></Field><Field label="Category"><select required name="category_id" defaultValue={productModal === "new" ? "" : productModal.category_id} className={input}><option value="" disabled>Select a category</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Selling price"><input required name="price" type="number" min="0" step="0.01" defaultValue={productModal === "new" ? 0 : productModal.price} className={input} /></Field><Field label="Tax rate (%)"><input required name="tax_rate" type="number" min="0" max="100" step="0.01" defaultValue={productModal === "new" ? 0 : productModal.tax_rate} className={input} /></Field><Field label="Cost price"><input required name="cost_price" type="number" min="0" step="0.01" defaultValue={productModal === "new" ? 0 : productModal.cost_price} className={input} /></Field><Field label="Sort order"><input required name="sort_order" type="number" step="1" defaultValue={productModal === "new" ? 0 : productModal.sort_order} className={input} /></Field><Field label="SKU"><input name="sku" defaultValue={productModal === "new" ? "" : productModal.sku || ""} className={input} /></Field><Field label="Barcode"><input name="barcode" defaultValue={productModal === "new" ? "" : productModal.barcode || ""} className={input} /></Field><Field label="Printer destination"><select name="printer_destination" defaultValue={productModal === "new" ? "internal" : productModal.printer_destination} className={input}><option value="internal">Internal</option><option value="none">None</option></select></Field><div className="space-y-2 pt-5"><label className="flex items-center gap-2 text-sm font-medium"><input name="track_inventory" type="checkbox" defaultChecked={productModal !== "new" && productModal.track_inventory} />Track inventory</label><label className="flex items-center gap-2 text-sm font-medium"><input name="active" type="checkbox" defaultChecked={productModal === "new" || productModal.active} />Active</label></div><div className="sm:col-span-2 flex justify-end"><Button disabled={pending} type="submit">{pending ? "Saving…" : "Save product"}</Button></div></form></Modal>}
  </div>;
}
