"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireProfile } from "@/lib/auth/user";
import { createClient } from "@/lib/supabase/server";
async function db(){ await requireProfile(); const s=await createClient(); const {data}=await s.rpc("user_has_permission",{required_permission:"inventory:manage"}); if(!data) throw new Error("You do not have permission to manage inventory."); return s; }
const item=z.object({id:z.string().uuid().optional(),name:z.string().trim().min(1),sku:z.string().nullable(),barcode:z.string().nullable(),category_id:z.string().uuid().nullable(),base_unit:z.enum(["piece","gram","kilogram","milliliter","liter"]),minimum_quantity:z.coerce.number().min(0),reorder_quantity:z.coerce.number().min(0),supplier_id:z.string().uuid().nullable(),track_inventory:z.boolean(),active:z.boolean(),notes:z.string()});
const msg=(e:{message:string;code?:string})=>e.code==="23505"?"That SKU, barcode, invoice, or name is already in use.":e.message;
const done=()=>{revalidatePath("/app/inventory");return {success:"Saved."};};
export async function saveStock(input:unknown){const x=item.safeParse(input);if(!x.success)return {error:x.error.issues[0].message};try{const s=await db();const a=x.data;const {error}=await s.rpc("save_stock_item",{p_id:a.id??null,p_name:a.name,p_sku:a.sku,p_barcode:a.barcode,p_category:a.category_id,p_unit:a.base_unit,p_minimum:a.minimum_quantity,p_reorder:a.reorder_quantity,p_supplier:a.supplier_id,p_track:a.track_inventory,p_active:a.active,p_notes:a.notes});if(error)return {error:msg(error)};return done()}catch(e){return {error:e instanceof Error?e.message:"Unable to save."}}}
export async function saveEntity(table:"inventory_categories"|"suppliers"|"product_recipes"|"purchases"|"purchase_items", values:Record<string,unknown>, id?:string){try{const s=await db();const {error}=id?await s.from(table).update(values).eq("id",id):await s.from(table).insert(values);if(error)return {error:msg(error)};return done()}catch(e){return {error:e instanceof Error?e.message:"Unable to save."}}}
export async function receivePurchase(id:string){try{const {error}=await (await db()).rpc("receive_purchase",{p_purchase:id});if(error)return {error:msg(error)};return done()}catch(e){return {error:e instanceof Error?e.message:"Unable to receive."}}}
export async function recordWaste(item:string,quantity:number,reason:string,note:string,allow=false){try{const {error}=await (await db()).rpc("record_inventory_waste",{p_item:item,p_quantity:quantity,p_reason:reason,p_note:note,p_allow_negative:allow});if(error)return {error:msg(error)};return done()}catch(e){return {error:e instanceof Error?e.message:"Unable to record waste."}}}
export async function adjust(item:string,kind:string,value:number,reason:string,note:string,allow=false){try{const {error}=await (await db()).rpc("adjust_inventory",{p_item:item,p_kind:kind,p_value:value,p_reason:reason,p_note:note,p_allow_negative:allow});if(error)return {error:msg(error)};return done()}catch(e){return {error:e instanceof Error?e.message:"Unable to adjust."}}}
export async function acknowledge(id:string){try{const s=await db();const {error}=await s.from("stock_alerts").update({acknowledged_at:new Date().toISOString()}).eq("id",id);if(error)return {error:msg(error)};return done()}catch(e){return {error:e instanceof Error?e.message:"Unable to acknowledge."}}}
