-- Inventory ledger and workflows. This is intentionally additive; balances change only through controlled functions.
create table public.inventory_categories (
 id uuid primary key default gen_random_uuid(), name text not null check (length(btrim(name)) between 1 and 100), sort_order integer not null default 0, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index inventory_categories_name_ci_unique on public.inventory_categories (lower(name));
create table public.suppliers (
 id uuid primary key default gen_random_uuid(), name text not null check(length(btrim(name)) between 1 and 160), contact_person text not null default '', phone text not null default '', email text not null default '', address text not null default '', tax_number text not null default '', notes text not null default '', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.stock_items (
 id uuid primary key default gen_random_uuid(), name text not null check(length(btrim(name)) between 1 and 160), sku text, barcode text, category_id uuid references public.inventory_categories(id) on delete restrict, base_unit text not null check(base_unit in ('piece','gram','kilogram','milliliter','liter')), current_quantity numeric(14,3) not null default 0, minimum_quantity numeric(14,3) not null default 0 check(minimum_quantity >= 0), reorder_quantity numeric(14,3) not null default 0 check(reorder_quantity >= 0), average_cost numeric(14,4) not null default 0 check(average_cost >= 0), last_purchase_cost numeric(14,4) not null default 0 check(last_purchase_cost >= 0), supplier_id uuid references public.suppliers(id) on delete set null, track_inventory boolean not null default true, active boolean not null default true, notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index stock_items_sku_unique on public.stock_items(sku) where sku is not null;
create unique index stock_items_barcode_unique on public.stock_items(barcode) where barcode is not null;
create index stock_items_category_idx on public.stock_items(category_id, active);
create table public.product_recipes (
 id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete restrict, stock_item_id uuid not null references public.stock_items(id) on delete restrict, quantity_required numeric(14,3) not null check(quantity_required > 0), waste_percentage numeric(6,3) not null default 0 check(waste_percentage >= 0 and waste_percentage <= 100), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(product_id, stock_item_id)
);
create table public.purchases (
 id uuid primary key default gen_random_uuid(), supplier_id uuid references public.suppliers(id) on delete restrict, invoice_number text, purchase_date date not null default current_date, received_at timestamptz, status text not null default 'draft' check(status in ('draft','received','cancelled')), notes text not null default '', created_by uuid not null default auth.uid() references public.profiles(id), total numeric(14,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check((status = 'received') = (received_at is not null))
);
create unique index purchases_supplier_invoice_unique on public.purchases(supplier_id, invoice_number) where invoice_number is not null;
create table public.purchase_items (id uuid primary key default gen_random_uuid(), purchase_id uuid not null references public.purchases(id) on delete cascade, stock_item_id uuid not null references public.stock_items(id) on delete restrict, quantity numeric(14,3) not null check(quantity > 0), unit text not null check(unit in ('piece','gram','kilogram','milliliter','liter')), unit_cost numeric(14,4) not null check(unit_cost >= 0), tax numeric(14,2) not null default 0 check(tax >= 0), line_total numeric(14,2) generated always as ((quantity * unit_cost) + tax) stored, unique(purchase_id, stock_item_id));
create table public.order_inventory_deductions (id uuid primary key default gen_random_uuid(), order_id uuid not null unique references public.orders(id) on delete restrict, idempotency_key text not null unique, completed_at timestamptz not null default now(), created_by uuid references public.profiles(id));
create table public.stock_movements (
 id uuid primary key default gen_random_uuid(), stock_item_id uuid not null references public.stock_items(id) on delete restrict, movement_type text not null check(movement_type in ('opening_balance','purchase','sale','internal_consumption','waste','adjustment_in','adjustment_out','return_to_supplier','correction','inventory_count')), quantity_delta numeric(14,3) not null check(quantity_delta <> 0), quantity_before numeric(14,3) not null, quantity_after numeric(14,3) not null, unit_cost numeric(14,4) not null default 0, total_cost numeric(14,4) not null default 0, reference_type text, reference_id uuid, order_id uuid references public.orders(id) on delete restrict, order_item_id uuid references public.order_items(id) on delete restrict, purchase_id uuid references public.purchases(id) on delete restrict, reason text, actor_id uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb
);
create index stock_movements_item_created_idx on public.stock_movements(stock_item_id, created_at desc);
create index stock_movements_order_idx on public.stock_movements(order_id) where order_id is not null;
create table public.stock_alerts (id uuid primary key default gen_random_uuid(), stock_item_id uuid not null references public.stock_items(id) on delete restrict, acknowledged_at timestamptz, acknowledged_by uuid references public.profiles(id), created_at timestamptz not null default now(), unique(stock_item_id));

create or replace function public.inventory_audit(p_action text, p_entity text, p_id text, p_before jsonb default null, p_after jsonb default null, p_reason text default null) returns void language plpgsql security definer set search_path=public as $$ begin insert into public.audit_log(actor_id,action,entity_type,entity_id,before_data,after_data,reason) values(auth.uid(),p_action,p_entity,p_id,p_before,p_after,p_reason); end $$;
create or replace function public.inventory_apply_movement(p_item uuid,p_type text,p_delta numeric,p_reason text default null,p_reference_type text default null,p_reference_id uuid default null,p_order uuid default null,p_order_item uuid default null,p_purchase uuid default null,p_metadata jsonb default '{}'::jsonb,p_allow_negative boolean default false,p_unit_cost numeric default null) returns void language plpgsql security definer set search_path=public as $$ declare v public.stock_items; v_after numeric; v_cost numeric; begin select * into v from public.stock_items where id=p_item for update; if not found then raise exception 'Stock item not found'; end if; v_after:=v.current_quantity+p_delta; if v_after < 0 and not p_allow_negative then raise exception 'Insufficient stock; confirm a negative adjustment to continue'; end if; v_cost:=coalesce(p_unit_cost,v.average_cost); insert into public.stock_movements(stock_item_id,movement_type,quantity_delta,quantity_before,quantity_after,unit_cost,total_cost,reference_type,reference_id,order_id,order_item_id,purchase_id,reason,actor_id,metadata) values(p_item,p_type,p_delta,v.current_quantity,v_after,v_cost,abs(p_delta)*v_cost,p_reference_type,p_reference_id,p_order,p_order_item,p_purchase,p_reason,auth.uid(),p_metadata); update public.stock_items set current_quantity=v_after where id=p_item; insert into public.stock_alerts(stock_item_id) select p_item where v_after <= v.minimum_quantity on conflict(stock_item_id) do update set acknowledged_at=null,acknowledged_by=null; end $$;
create or replace function public.receive_purchase(p_purchase uuid) returns void language plpgsql security definer set search_path=public as $$ declare p public.purchases; l record; s public.stock_items; begin if not public.user_has_permission('inventory:manage') then raise exception 'Not authorized'; end if; select * into p from public.purchases where id=p_purchase for update; if not found or p.status <> 'draft' then raise exception 'Only draft purchases can be received'; end if; for l in select * from public.purchase_items where purchase_id=p_purchase loop select * into s from public.stock_items where id=l.stock_item_id for update; perform public.inventory_apply_movement(l.stock_item_id,'purchase',l.quantity,'Purchase receipt','purchase',p_purchase,null,null,p_purchase,jsonb_build_object('unit',l.unit),false,l.unit_cost); update public.stock_items set average_cost=case when s.current_quantity+l.quantity=0 then l.unit_cost else ((s.current_quantity*s.average_cost)+(l.quantity*l.unit_cost))/(s.current_quantity+l.quantity) end,last_purchase_cost=l.unit_cost where id=l.stock_item_id; end loop; update public.purchases set status='received',received_at=now(),total=coalesce((select sum(line_total) from public.purchase_items where purchase_id=p_purchase),0) where id=p_purchase; perform public.inventory_audit('purchase_received','purchase',p_purchase::text,null,to_jsonb(p),'Purchase received'); end $$;
create or replace function public.record_inventory_waste(p_item uuid,p_quantity numeric,p_reason text,p_note text default '',p_allow_negative boolean default false) returns void language plpgsql security definer set search_path=public as $$ begin if not public.user_has_permission('inventory:manage') or p_quantity <= 0 or p_reason not in ('expired','damaged','spoiled','preparation_error','dropped','staff_consumption','other') then raise exception 'Invalid waste request'; end if; perform public.inventory_apply_movement(p_item,'waste',-p_quantity,p_reason,'waste',null,null,null,null,jsonb_build_object('note',p_note),p_allow_negative); perform public.inventory_audit('waste_recorded','stock_item',p_item::text,null,null,p_reason); end $$;
create or replace function public.adjust_inventory(p_item uuid,p_kind text,p_value numeric,p_reason text,p_note text default '',p_allow_negative boolean default false) returns void language plpgsql security definer set search_path=public as $$ declare s public.stock_items; d numeric; begin if not public.user_has_permission('inventory:manage') or nullif(btrim(p_reason),'') is null then raise exception 'A reason is required'; end if; select * into s from public.stock_items where id=p_item; if p_kind='set_count' then d:=p_value-s.current_quantity; elsif p_kind='increase' then d:=p_value; elsif p_kind='decrease' then d:=-p_value; else raise exception 'Invalid adjustment type'; end if; if d=0 then raise exception 'Adjustment does not change stock'; end if; perform public.inventory_apply_movement(p_item,case when p_kind='set_count' then 'inventory_count' when d>0 then 'adjustment_in' else 'adjustment_out' end,d,p_reason,'adjustment',null,null,null,null,jsonb_build_object('note',p_note),p_allow_negative); perform public.inventory_audit('adjustment_created','stock_item',p_item::text,to_jsonb(s),null,p_reason); end $$;
create or replace function public.deduct_order_inventory(p_order uuid) returns void language plpgsql security definer set search_path=public as $$ declare oi record; r record; t text; begin select status::text into t from public.orders where id=p_order for update; if t not in ('paid','internal_only') then return; end if; insert into public.order_inventory_deductions(order_id,idempotency_key,created_by) values(p_order,'order-inventory:'||p_order::text,auth.uid()) on conflict(order_id) do nothing; if not found then return; end if; for oi in select * from public.order_items where order_id=p_order and deleted_at is null and status='active' loop for r in select pr.*,si.name,si.base_unit,si.average_cost from public.product_recipes pr join public.stock_items si on si.id=pr.stock_item_id where pr.product_id=oi.product_id and pr.active loop perform public.inventory_apply_movement(r.stock_item_id,case when t='internal_only' then 'internal_consumption' else 'sale' end,-(oi.quantity*r.quantity_required*(1+r.waste_percentage/100)),'Completed order','order',p_order,p_order,oi.id,null,jsonb_build_object('recipe_id',r.id,'stock_item_name',r.name,'quantity_required',r.quantity_required,'waste_percentage',r.waste_percentage,'unit',r.base_unit,'product_id',oi.product_id),true,r.average_cost); end loop; end loop; end $$;
create or replace function public.inventory_order_completion_trigger() returns trigger language plpgsql security definer set search_path=public as $$ begin if new.status::text in ('paid','internal_only') and (tg_op='INSERT' or old.status::text not in ('paid','internal_only')) then perform public.deduct_order_inventory(new.id); end if; return new; end $$;
create trigger orders_deduct_inventory after insert or update of status on public.orders for each row execute procedure public.inventory_order_completion_trigger();

create trigger inventory_categories_updated before update on public.inventory_categories for each row execute procedure public.set_updated_at(); create trigger suppliers_updated before update on public.suppliers for each row execute procedure public.set_updated_at(); create trigger stock_items_updated before update on public.stock_items for each row execute procedure public.set_updated_at(); create trigger recipes_updated before update on public.product_recipes for each row execute procedure public.set_updated_at(); create trigger purchases_updated before update on public.purchases for each row execute procedure public.set_updated_at();
alter table public.inventory_categories enable row level security; alter table public.suppliers enable row level security; alter table public.stock_items enable row level security; alter table public.product_recipes enable row level security; alter table public.purchases enable row level security; alter table public.purchase_items enable row level security; alter table public.stock_movements enable row level security; alter table public.stock_alerts enable row level security; alter table public.order_inventory_deductions enable row level security;
create policy inventory_categories_manage on public.inventory_categories for all to authenticated using(public.user_has_permission('inventory:manage')) with check(public.user_has_permission('inventory:manage')); create policy suppliers_manage on public.suppliers for all to authenticated using(public.user_has_permission('inventory:manage')) with check(public.user_has_permission('inventory:manage')); create policy stock_items_manage on public.stock_items for select to authenticated using(public.user_has_permission('inventory:manage')); create policy recipes_manage on public.product_recipes for all to authenticated using(public.user_has_permission('inventory:manage')) with check(public.user_has_permission('inventory:manage')); create policy purchases_manage on public.purchases for all to authenticated using(public.user_has_permission('inventory:manage')) with check(public.user_has_permission('inventory:manage')); create policy purchase_items_manage on public.purchase_items for all to authenticated using(public.user_has_permission('inventory:manage')) with check(public.user_has_permission('inventory:manage')); create policy movements_read on public.stock_movements for select to authenticated using(public.user_has_permission('inventory:manage')); create policy alerts_manage on public.stock_alerts for all to authenticated using(public.user_has_permission('inventory:manage')) with check(public.user_has_permission('inventory:manage')); create policy deductions_read on public.order_inventory_deductions for select to authenticated using(public.user_has_permission('inventory:manage'));
grant execute on function public.receive_purchase(uuid),public.record_inventory_waste(uuid,numeric,text,text,boolean),public.adjust_inventory(uuid,text,numeric,text,text,boolean) to authenticated;
create or replace function public.save_stock_item(p_id uuid,p_name text,p_sku text,p_barcode text,p_category uuid,p_unit text,p_minimum numeric,p_reorder numeric,p_supplier uuid,p_track boolean,p_active boolean,p_notes text) returns uuid language plpgsql security definer set search_path=public as $$ declare x uuid; begin if not public.user_has_permission('inventory:manage') then raise exception 'Not authorized'; end if; if nullif(btrim(p_name),'') is null or p_unit not in ('piece','gram','kilogram','milliliter','liter') or p_minimum<0 or p_reorder<0 then raise exception 'Invalid stock item'; end if; if p_id is null then insert into public.stock_items(name,sku,barcode,category_id,base_unit,minimum_quantity,reorder_quantity,supplier_id,track_inventory,active,notes) values(btrim(p_name),nullif(btrim(p_sku),''),nullif(btrim(p_barcode),''),p_category,p_unit,p_minimum,p_reorder,p_supplier,p_track,p_active,coalesce(p_notes,'')) returning id into x; perform public.inventory_audit('stock_item_created','stock_item',x::text,null,null,null); else update public.stock_items set name=btrim(p_name),sku=nullif(btrim(p_sku),''),barcode=nullif(btrim(p_barcode),''),category_id=p_category,base_unit=p_unit,minimum_quantity=p_minimum,reorder_quantity=p_reorder,supplier_id=p_supplier,track_inventory=p_track,active=p_active,notes=coalesce(p_notes,'') where id=p_id returning id into x; if not found then raise exception 'Stock item not found'; end if; perform public.inventory_audit('stock_item_edited','stock_item',x::text,null,null,null); end if; return x; end $$;
grant execute on function public.save_stock_item(uuid,text,text,text,uuid,text,numeric,numeric,uuid,boolean,boolean,text) to authenticated;
